// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: google/cloud/bigquery/storage/v1/annotations.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

// MARK: - Extension support defined in annotations.proto.

// MARK: - Extension Properties

// Swift Extensions on the extended Messages to add easy access to the declared
// extension fields. The names are based on the extension field name from the proto
// declaration. To avoid naming collisions, the names are prefixed with the name of
// the scope where the extend directive occurs.

extension SwiftProtobuf.Google_Protobuf_FieldOptions {

  /// Setting the column_name extension allows users to reference
  /// bigquery column independently of the field name in the protocol buffer
  /// message.
  ///
  /// The intended use of this annotation is to reference a destination column
  /// named using characters unavailable for protobuf field names (e.g. unicode
  /// characters).
  ///
  /// More details about BigQuery naming limitations can be found here:
  /// https://cloud.google.com/bigquery/docs/schemas#column_names
  ///
  /// This extension is currently experimental.
  package var Google_Cloud_Bigquery_Storage_V1_columnName: String {
    get {return getExtensionValue(ext: Google_Cloud_Bigquery_Storage_V1_Extensions_column_name) ?? String()}
    set {setExtensionValue(ext: Google_Cloud_Bigquery_Storage_V1_Extensions_column_name, value: newValue)}
  }
  /// Returns true if extension `Google_Cloud_Bigquery_Storage_V1_Extensions_column_name`
  /// has been explicitly set.
  package var hasGoogle_Cloud_Bigquery_Storage_V1_columnName: Bool {
    return hasExtensionValue(ext: Google_Cloud_Bigquery_Storage_V1_Extensions_column_name)
  }
  /// Clears the value of extension `Google_Cloud_Bigquery_Storage_V1_Extensions_column_name`.
  /// Subsequent reads from it will return its default value.
  package mutating func clearGoogle_Cloud_Bigquery_Storage_V1_columnName() {
    clearExtensionValue(ext: Google_Cloud_Bigquery_Storage_V1_Extensions_column_name)
  }

}

// MARK: - File's ExtensionMap: Google_Cloud_Bigquery_Storage_V1_Annotations_Extensions

/// A `SwiftProtobuf.SimpleExtensionMap` that includes all of the extensions defined by
/// this .proto file. It can be used any place an `SwiftProtobuf.ExtensionMap` is needed
/// in parsing, or it can be combined with other `SwiftProtobuf.SimpleExtensionMap`s to create
/// a larger `SwiftProtobuf.SimpleExtensionMap`.
package let Google_Cloud_Bigquery_Storage_V1_Annotations_Extensions: SwiftProtobuf.SimpleExtensionMap = [
  Google_Cloud_Bigquery_Storage_V1_Extensions_column_name
]

// Extension Objects - The only reason these might be needed is when manually
// constructing a `SimpleExtensionMap`, otherwise, use the above _Extension Properties_
// accessors for the extension fields on the messages directly.

/// Setting the column_name extension allows users to reference
/// bigquery column independently of the field name in the protocol buffer
/// message.
///
/// The intended use of this annotation is to reference a destination column
/// named using characters unavailable for protobuf field names (e.g. unicode
/// characters).
///
/// More details about BigQuery naming limitations can be found here:
/// https://cloud.google.com/bigquery/docs/schemas#column_names
///
/// This extension is currently experimental.
package let Google_Cloud_Bigquery_Storage_V1_Extensions_column_name = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalExtensionField<SwiftProtobuf.ProtobufString>, SwiftProtobuf.Google_Protobuf_FieldOptions>(
  _protobuf_fieldNumber: 454943157,
  fieldName: "google.cloud.bigquery.storage.v1.column_name"
)
