// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: google/cloud/bigquery/v2/udf_resource.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

///
/// This is used for defining User Defined Function (UDF) resources only when
/// using legacy SQL.  Users of GoogleSQL should leverage either DDL (e.g.
/// CREATE [TEMPORARY] FUNCTION ... ) or the Routines API to define UDF
/// resources.
///
/// For additional information on migrating, see:
/// https://cloud.google.com/bigquery/docs/reference/standard-sql/migrating-from-legacy-sql#differences_in_user-defined_javascript_functions
package struct Google_Cloud_Bigquery_V2_UserDefinedFunctionResource: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// [Pick one] A code resource to load from a Google Cloud Storage URI
  /// (gs://bucket/path).
  package var resourceUri: SwiftProtobuf.Google_Protobuf_StringValue {
    get {return _resourceUri ?? SwiftProtobuf.Google_Protobuf_StringValue()}
    set {_resourceUri = newValue}
  }
  /// Returns true if `resourceUri` has been explicitly set.
  package var hasResourceUri: Bool {return self._resourceUri != nil}
  /// Clears the value of `resourceUri`. Subsequent reads from it will return its default value.
  package mutating func clearResourceUri() {self._resourceUri = nil}

  /// [Pick one] An inline resource that contains code for a user-defined
  /// function (UDF). Providing a inline code resource is equivalent to providing
  /// a URI for a file containing the same code.
  package var inlineCode: SwiftProtobuf.Google_Protobuf_StringValue {
    get {return _inlineCode ?? SwiftProtobuf.Google_Protobuf_StringValue()}
    set {_inlineCode = newValue}
  }
  /// Returns true if `inlineCode` has been explicitly set.
  package var hasInlineCode: Bool {return self._inlineCode != nil}
  /// Clears the value of `inlineCode`. Subsequent reads from it will return its default value.
  package mutating func clearInlineCode() {self._inlineCode = nil}

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  package init() {}

  fileprivate var _resourceUri: SwiftProtobuf.Google_Protobuf_StringValue? = nil
  fileprivate var _inlineCode: SwiftProtobuf.Google_Protobuf_StringValue? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "google.cloud.bigquery.v2"

extension Google_Cloud_Bigquery_V2_UserDefinedFunctionResource: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".UserDefinedFunctionResource"
  package static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "resource_uri"),
    2: .standard(proto: "inline_code"),
  ]

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._resourceUri) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._inlineCode) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._resourceUri {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._inlineCode {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Google_Cloud_Bigquery_V2_UserDefinedFunctionResource, rhs: Google_Cloud_Bigquery_V2_UserDefinedFunctionResource) -> Bool {
    if lhs._resourceUri != rhs._resourceUri {return false}
    if lhs._inlineCode != rhs._inlineCode {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
